### PR TITLE
update for mupdf 1.6 / openjpeg 2.1

### PR DESCRIPTION
**Pull request by zmike**
doesn't work due to some mupdf changes, but compiles and loads the module without issues

### CODE REVIEW

**Comment by vtorri** [comment]
i've integrated mupdf 1.10a; i've just have to fix the m4 file

**Comment by ThierryHFR** [comment]
Compilation Failed:
src/modules/pdf/mupdf-1.6/source/fitz/.libs/src_modules_pdf_module_la-load-jpx.o: In function `fz_load_jpx':
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:98: undefined reference to `opj_set_default_decoder_parameters'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:102: undefined reference to `opj_create_decompress'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:103: undefined reference to `opj_set_info_handler'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:104: undefined reference to `opj_set_warning_handler'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:105: undefined reference to `opj_set_error_handler'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:106: undefined reference to `opj_setup_decoder'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:112: undefined reference to `opj_stream_default_create'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:117: undefined reference to `opj_stream_set_read_function'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:118: undefined reference to `opj_stream_set_skip_function'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:119: undefined reference to `opj_stream_set_seek_function'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:120: undefined reference to `opj_stream_set_user_data'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:122: undefined reference to `opj_stream_set_user_data_length'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:124: undefined reference to `opj_read_header'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:131: undefined reference to `opj_decode'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:139: undefined reference to `opj_stream_destroy'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:140: undefined reference to `opj_destroy_codec'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:234: undefined reference to `opj_image_destroy'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:211: undefined reference to `opj_image_destroy'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:126: undefined reference to `opj_stream_destroy'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:127: undefined reference to `opj_destroy_codec'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:133: undefined reference to `opj_stream_destroy'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:134: undefined reference to `opj_destroy_codec'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:135: undefined reference to `opj_image_destroy'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:150: undefined reference to `opj_image_destroy'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:155: undefined reference to `opj_image_destroy'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:160: undefined reference to `opj_image_destroy'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:165: undefined reference to `opj_image_destroy'
/root/etui/src/modules/pdf/mupdf-1.6/source/fitz/load-jpx.c:108: undefined reference to `opj_destroy_codec'
/usr/bin/ld: src/modules/pdf/.libs/module.so: hidden symbol `opj_setup_decoder' isn't defined
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:3723 : la recette pour la cible « src/modules/pdf/module.la » a échouée
make[1]: *** [src/modules/pdf/module.la] Erreur 1
make[1] : on quitte le répertoire « /root/etui »
Makefile:2195 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

**Comment by vtorri** [comment]
please wait a bit : i'm in the process of rewriting the internal modules and smart object and it takes a bit of time

**Comment by ThierryHFR** [comment]
Ok, I'll wait, I'm very interested in your project.

**Pull request closed without merging**
